services:
  backend:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
      dockerfile: Dockerfile.dev
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
